name: must_be
description: Validate your data similarly to a framework for checking values in tests.
version: 0.1.0
homepage: https://github.com/kmartins/must_be
repository: https://github.com/kmartins/must_be

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  meta: ^1.9.0
  test: ^1.19.2

dev_dependencies:
  very_good_analysis: ^4.0.0
