name: must_be
description: Validate your data similarly to a framework for checking values in tests.
version: 0.2.0
homepage: https://github.com/kmartins/must_be
repository: https://github.com/kmartins/must_be

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.10.0
  test: ^1.24.7

dev_dependencies:
  very_good_analysis: ^5.1.0
