name: Must be

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: kmartins/workflows/.github/workflows/semantic_pull_request.yaml@semantic_pr-v1.0.1
    with:
      types: "feat, fix, deps, docs, style, refactor, perf, test, build, ci, revert"

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      min_coverage: 99

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
