name: Must be

on:
  push:
    branches:
      - main
    paths:
      - "must_be/**"
      - ".github/workflows/must_be.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "must_be/**"
      - ".github/workflows/must_be.yaml"

jobs:
  build:
    uses: kmartins/workflows/.github/workflows/dart_package.yaml@v1.0.0
    with:
      working_directory: must_be
      check_coverage: false

  pana:
    uses: kmartins/workflows/.github/workflows/pana.yaml@v1.0.0
    with:
      working_directory: must_be